class ICICIDirectURL:
    MarketInsights = "https://www.icicidirect.com/research/equity/market-insights"
    CorporateActions = "https://www.icicidirect.com/research/equity/corporate-actions"
    TrendingNews = "https://www.icicidirect.com/research/equity/trending-news"
    TradingIdeas = "https://www.icicidirect.com/research/equity/trading-ideas"
    InvestingIdeas = "https://www.icicidirect.com/research/equity/investing-ideas"
    SectorPerformance = "https://www.icicidirect.com/equity/sector-performance/nse"

class MoneyControlRSSURL:
    TopNews = "https://www.moneycontrol.com/rss/MCtopnews.xml"
    Budget = "https://www.moneycontrol.com/rss/budget2013.xml"
    LatestNews = "https://www.moneycontrol.com/rss/latestnews.xml"
    PopularNews = "https://www.moneycontrol.com/rss/mostpopular.xml"
    BusinessNews = "https://www.moneycontrol.com/rss/business.xml"
    PersonalFinance = "https://www.moneycontrol.com/rss/pfcolumns.xml"
    BrokersRecommendations = "https://www.moneycontrol.com/rss/brokeragerecos.xml"
    BuzzingStocks = "https://www.moneycontrol.com/rss/buzzingstocks.xml"
    Economy = "https://www.moneycontrol.com/rss/economy.xml"
    MarketReports = "https://www.moneycontrol.com/rss/marketreports.xml"
    ADRs = "https://www.moneycontrol.com/rss/indianadrs.xml"
    GlobalMarkets = "https://www.moneycontrol.com/rss/internationalmarkets.xml"
    MarketEdge = "https://www.moneycontrol.com/rss/marketedge.xml"
    MarketOutlook = "https://www.moneycontrol.com/rss/marketoutlook.xml"
    Technicals = "https://www.moneycontrol.com/rss/technicals.xml"
    IPONews = "https://www.moneycontrol.com/rss/iponews.xml"
    InsuranceNews = "https://www.moneycontrol.com/rss/insurancenews.xml"
    MutualFundNews = "https://www.moneycontrol.com/rss/mfnews.xml"
    NRINews = "https://www.moneycontrol.com/rss/nrinews.xml"
    CommodityNews = "https://www.moneycontrol.com/rss/commodities.xml"
    Results = "https://www.moneycontrol.com/rss/results.xml"
    TechnologyNews = "https://www.moneycontrol.com/rss/technology.xml"
    EntertainmentNews = "https://www.moneycontrol.com/rss/entertainment.xml"
    WorldNews = "https://www.moneycontrol.com/rss/worldnews.xml"
    SportsNews = "https://www.moneycontrol.com/rss/sports.xml"
    CurrentAffairs = "https://www.moneycontrol.com/rss/currentaffairs.xml"
    CurrencyNews = "https://www.moneycontrol.com/rss/currency.xml"

class KotakSecuritiesURL:
    basePDFLink =  "https://www.kotaksecurities.com/ksweb/php/showpdf.php?q="
    reportLink = "https://www.kotaksecurities.com/ktrade/kreport.exe?"

class ZerodhaURL:
    loginURL = "https://kite.zerodha.com"

class NSEScripsURL:
    auto = "https://www1.nseindia.com/content/indices/ind_niftyautolist.csv"
    bank = "https://www1.nseindia.com/content/indices/ind_niftybanklist.csv"
    consdu = "https://www1.nseindia.com/content/indices/ind_niftyconsumerdurableslist.csv"
    finserv = "https://www1.nseindia.com/content/indices/ind_niftyfinancelist.csv"
    finserv50 = "https://www1.nseindia.com/content/indices/ind_niftyfinancialservices25_50list.csv"
    fmcg = "https://www1.nseindia.com/content/indices/ind_niftyfmcglist.csv"
    health = "https://www1.nseindia.com/content/indices/ind_niftyhealthcarelist.csv"
    it = "https://www1.nseindia.com/content/indices/ind_niftyitlist.csv"
    media = "https://www1.nseindia.com/content/indices/ind_niftymedialist.csv"
    metal = "https://www1.nseindia.com/content/indices/ind_niftymetallist.csv"
    oil = "https://www1.nseindia.com/content/indices/ind_niftyoilgaslist.csv"
    pharma = "https://www1.nseindia.com/content/indices/ind_niftypharmalist.csv"
    privatebank = "https://www1.nseindia.com/content/indices/ind_nifty_privatebanklist.csv"
    psu = "https://www1.nseindia.com/content/indices/ind_niftypsubanklist.csv"
    realty = "https://www1.nseindia.com/content/indices/ind_niftyrealtylist.csv"