class ZerodhaXPaths:
    passInputID = "password"
    userInputID = "userid"
    loginButton = "/html/body/div[1]/div/div/div[1]/div/div/div/form/div[4]/button"
    pinInputID = '//*[@id="pin"]'
    verifyButton = "/html/body/div[1]/div/div/div[1]/div/div/div/form/div[3]/button"
    searchInput =  "/html/body/div[1]/div[2]/div[1]/div/div[1]/div/div/input"
    selectSymbol = "/html/body/div[1]/div[2]/div[1]/div/div[1]/ul/div/li[1]"
    marketDepthButton = "/html/body/div[1]/div[2]/div[1]/div/div[1]/ul/div/li[1]/span[3]/button[4]"
    viewMoreButton = "/html/body/div[1]/div[5]/div/div/div[2]/div/div/div[1]/div[2]"
    bidsTables = "/html/body/div[1]/div[5]/div/div/div[2]/div/div/div[1]/div[1]/table[1]/tbody"
    totalBid = "/html/body/div[1]/div[5]/div/div/div[2]/div/div/div[1]/div[1]/table[1]/tfoot"
    asksTable = "/html/body/div[1]/div[5]/div/div/div[2]/div/div/div[1]/div[1]/table[2]/tbody"
    totalAsk = "/html/body/div[1]/div[5]/div/div/div[2]/div/div/div[1]/div[1]/table[2]/tfoot"
    ltp = "/html/body/div[1]/div[5]/div/div/div[1]/div/div[2]/div[2]/span/span[1]"
    ltq = '/html/body/div[1]/div[5]/div/div/div[2]/div/div/div[2]/div[4]/div[1]/span'
    orderBookElement = '/html/body/div[1]/div[5]/div/div/div[2]/div/div/div[1]/div[1]/table[1]/tbody/tr[8]'
    orderBookSearch = '/html/body/div[1]/div[5]/div/div/div[1]/div/div[1]/div/div/div/input'
    orderBookResult = '/html/body/div[1]/div[5]/div/div/div[1]/div/div[1]/div/ul/div/li[1]'